
cc_library(
    name = "testing",
    srcs = [
        "input_iterator_p.h",
        "multipass_input_iterator_p.h",
        "output_iterator_p.h",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"],
    includes = ["."],
    deps = [
        "//lib/roo_io:testing",
    ],
)

