cc_test(
    name = "byte_order_test",
    srcs = [
        "byte_order_test.cpp",
    ],
    copts = ["-Iexternal/gtest/include"],
    linkstatic = 1,
    deps = [
        "//lib/roo_io:testing",
    ],
)

cc_test(
    name = "reader_test",
    srcs = [
        "reader_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//lib/roo_io:testing",
    ],
)
