
cc_test(
    name = "fill_test",
    srcs = [
        "fill_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//lib/roo_io:testing",
    ],
)

cc_test(
    name = "load_test",
    srcs = [
        "load_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//lib/roo_io:testing",
    ],
)
