
cc_test(
    name = "fill_test",
    srcs = [
        "fill_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//lib/roo_io:testing",
    ],
)

cc_test(
    name = "load_test",
    srcs = [
        "load_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//lib/roo_io:testing",
    ],
)

cc_test(
    name = "store_test",
    srcs = [
        "store_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//lib/roo_io:testing",
    ],
)

cc_test(
    name = "unsafe_memory_input_iterator_test",
    srcs = [
        "unsafe_memory_input_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//lib/roo_io/test:testing",
    ],
)

cc_test(
    name = "memory_input_iterator_test",
    srcs = [
        "memory_input_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//lib/roo_io/test:testing",
    ],
)

cc_test(
    name = "multipass_memory_input_iterator_test",
    srcs = [
        "multipass_memory_input_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//lib/roo_io/test:testing",
    ],
)

cc_test(
    name = "memory_output_iterator_test",
    srcs = [
        "memory_output_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//lib/roo_io/test:testing",
    ],
)

cc_test(
    name = "memory_iterable_test",
    srcs = [
        "memory_iterable_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//lib/roo_io/test:testing",
    ],
)
