load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_test(
    name = "fill_test",
    size = "small",
    srcs = [
        "fill_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//:testing",
    ],
)

cc_test(
    name = "load_test",
    size = "small",
    srcs = [
        "load_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//:testing",
    ],
)

cc_test(
    name = "store_test",
    size = "small",
    srcs = [
        "store_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//:testing",
    ],
)

cc_test(
    name = "unsafe_memory_input_iterator_test",
    size = "small",
    srcs = [
        "unsafe_memory_input_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//test:testing",
    ],
)

cc_test(
    name = "memory_input_iterator_test",
    size = "small",
    srcs = [
        "memory_input_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//test:testing",
    ],
)

cc_test(
    name = "multipass_memory_input_iterator_test",
    size = "small",
    srcs = [
        "multipass_memory_input_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//test:testing",
    ],
)

cc_test(
    name = "memory_output_iterator_test",
    size = "small",
    srcs = [
        "memory_output_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//test:testing",
    ],
)

cc_test(
    name = "memory_iterable_test",
    size = "small",
    srcs = [
        "memory_iterable_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//test:testing",
    ],
)
