load("@roo_testing//roo_testing/emulation:arduino.bzl", "roo_arduino_example")

roo_arduino_example(
    name = "Serial",
    sketch = "Serial.ino",
    deps = [
        "//:arduino_stream",
        "//:roo_io",
    ],
)
