cc_test(
    name = "buffered_input_stream_iterator_test",
    srcs = [
        "buffered_input_stream_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//lib/roo_io/test:testing",
    ],
)

cc_test(
    name = "buffered_output_stream_iterator_test",
    srcs = [
        "buffered_output_stream_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//lib/roo_io/test:testing",
    ],
)

cc_test(
    name = "buffered_multipass_input_stream_iterator_test",
    srcs = [
        "buffered_multipass_input_stream_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//lib/roo_io/test:testing",
    ],
)
