load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_test(
    name = "buffered_input_stream_iterator_test",
    size = "small",
    srcs = [
        "buffered_input_stream_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//test:testing",
    ],
)

cc_test(
    name = "buffered_output_stream_iterator_test",
    size = "small",
    srcs = [
        "buffered_output_stream_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//test:testing",
    ],
)

cc_test(
    name = "buffered_multipass_input_stream_iterator_test",
    size = "small",
    srcs = [
        "buffered_multipass_input_stream_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//test:testing",
    ],
)

cc_test(
    name = "limited_input_test",
    size = "small",
    srcs = ["limited_input_test.cpp"],
    linkstatic = 1,
    deps = ["//test:testing"],
)

cc_test(
    name = "counting_output_sink_test",
    size = "small",
    srcs = ["counting_output_sink_test.cpp"],
    linkstatic = 1,
    deps = ["//test:testing"],
)

cc_test(
    name = "limited_output_iterator_test",
    size = "small",
    srcs = ["limited_output_iterator_test.cpp"],
    linkstatic = 1,
    deps = ["//test:testing"],
)

cc_test(
    name = "counting_iterator_test",
    size = "small",
    srcs = ["counting_iterator_test.cpp"],
    linkstatic = 1,
    deps = ["//test:testing"],
)
