load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_test(
    name = "buffered_input_stream_iterator_test",
    srcs = [
        "buffered_input_stream_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//test:testing",
    ],
)

cc_test(
    name = "buffered_output_stream_iterator_test",
    srcs = [
        "buffered_output_stream_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//test:testing",
    ],
)

cc_test(
    name = "buffered_multipass_input_stream_iterator_test",
    srcs = [
        "buffered_multipass_input_stream_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//test:testing",
    ],
)
