
cc_test(
    name = "memory_input_iterator_test",
    srcs = [
        "memory_input_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//lib/roo_io:testing",
    ],
)

cc_test(
    name = "memory_output_iterator_test",
    srcs = [
        "memory_output_iterator_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//lib/roo_io:testing",
    ],
)
