
cc_test(
    name = "ringbuffer_test",
    srcs = [
        "ringbuffer_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//test:testing",
    ],
    size = "small",
)

cc_test(
    name = "ringpipe_test",
    srcs = [
        "ringpipe_test.cpp",
    ],
    linkstatic = 1,
    deps = [
        "//test:testing",
    ],
    size = "small",
)
